# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 05:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=1200, verbose_name='Please provide some comments on what it was like to work with this person'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ques1',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='How much did you enjoy working with this person (1-5)? (5 = most)?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ques2',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='How much did you learn from this individual while working with them (1-5)? (5 = most)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ques3',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='How competent is this person in their domain of expertise (1-5)? (5 = most)'),
        ),
    ]
