# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('user', 'employee')]),
        ),
    ]
