# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20160619_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='work_again',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='would you work with this person again'),
        ),
    ]
