# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20160712_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ques2',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='How competent is this person in their domain of expertise (1-5)? (5 = most)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ques3',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='How much did you learn from this individual while working with them (1-5)? (5 = most)'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='level',
            field=models.CharField(max_length=15),
        ),
    ]
