# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20160719_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevel',
            name='office',
            field=models.CharField(default='Atlanta', max_length=15),
        ),
    ]
