# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_userlevel_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevel',
            name='office',
            field=models.CharField(max_length=15),
        ),
    ]
