# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20160719_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevel',
            name='service_area',
            field=models.CharField(default='S&O', max_length=15),
        ),
    ]
