# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20160619_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='downvotes',
        ),
        migrations.AlterField(
            model_name='vote',
            name='upvotes',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
