# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_userlevel_service_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevel',
            name='service_area',
            field=models.CharField(max_length=15),
        ),
    ]
