# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20160619_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='downvotes',
            field=models.NullBooleanField(),
        ),
    ]
