# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20160719_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='service_Line',
            field=models.CharField(default='', max_length=120),
        ),
    ]
