# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_vote_downvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='upvotes',
            field=models.NullBooleanField(),
        ),
    ]
