# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20160619_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeevoted', to='reviews.Employee'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votereview', to='reviews.Review'),
        ),
    ]
