# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20160807_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
