# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_remove_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='service_line',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
