# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_auto_20160807_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_active',
            new_name='is_live',
        ),
    ]
