# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_auto_20160808_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tracking_id',
            field=models.IntegerField(default=1),
        ),
    ]
