# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_employee_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tracking_id',
            field=models.IntegerField(),
        ),
    ]
