# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 02:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_auto_20160823_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=1500, validators=[django.core.validators.MinLengthValidator(60, message='Please enter a more impactful review')], verbose_name='Please provide some comments on what it was like to work with this person'),
        ),
    ]
